services:
  caddy:
    image: pocat/naiveproxy
    container_name: naiveproxy-server
    restart: always
    network_mode: host
    environment:
      - CADDYFILE=/etc/naiveproxy/Caddyfile
    volumes:
      - ./Caddyfile:/etc/naiveproxy/Caddyfile:ro
      - ./log/caddy:/var/log/caddy

  frps:
    image: snowdreamtech/frps
    container_name: frps
    restart: always
    network_mode: host
    volumes:
      - ./frps.ini:/frp/frps.ini:ro
    command: ["frps", "-c", "/frp/frps.ini"]