# frps.toml
bindPort = 7000         # [必选] 绑定端口, 客户端与该端口建立连接
log.to = "console"      # [可选] 日志配置, 通过打印的方式输出日志

# 身份验证
auth.method = "token"   # [可选] 身份验证方式
auth.token = "h93NSjR-Fi%jdy7s_82x" # [可选] token 设置, 只有客服端设置了相同 token 才能身份校验通过, 其实就是密码

# 下面是服务端仪表板配置
webServer.port = 7300        # 端口设置
webServer.addr = "0.0.0.0"   # IP 设置
webServer.user = "zqian"     # 仪表盘用户名设置
webServer.password = "Zq567711" # 仪表盘用户密码设置

